In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


In [2]:
scalar = torch.tensor(5)
scalar

tensor(5)

**we get scalar number from tensor from dimension**

In [3]:
scalar.ndim
scalar.item()

5

In [4]:
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
matrix = torch.tensor([[3,5],
                       [4,2]])
matrix

tensor([[3, 5],
        [4, 2]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
print(matrix[1])
matrix[0]

tensor([4, 2])


tensor([3, 5])

In [11]:
TENSOR = torch.tensor([[[3,4,2],
                        [6,2,8],
                        [3,8,9]]])
TENSOR

tensor([[[3, 4, 2],
         [6, 2, 8],
         [3, 8, 9]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR.ndim

3

In [14]:
random_tensor = torch.rand(4,4,5)
random_tensor

tensor([[[0.2240, 0.8699, 0.3206, 0.0758, 0.6792],
         [0.9726, 0.4508, 0.2525, 0.5328, 0.6321],
         [0.4633, 0.3230, 0.4964, 0.7531, 0.4459],
         [0.7375, 0.1018, 0.1540, 0.8069, 0.7746]],

        [[0.4789, 0.4610, 0.5464, 0.0701, 0.1744],
         [0.2909, 0.1926, 0.2396, 0.5279, 0.3379],
         [0.1102, 0.5562, 0.2043, 0.5366, 0.7605],
         [0.7786, 0.4391, 0.0069, 0.7718, 0.6452]],

        [[0.0880, 0.2627, 0.5610, 0.4960, 0.4539],
         [0.1489, 0.5718, 0.2038, 0.8879, 0.2296],
         [0.0405, 0.2195, 0.1645, 0.9410, 0.6124],
         [0.7463, 0.6505, 0.6328, 0.9519, 0.5487]],

        [[0.7055, 0.6126, 0.5504, 0.8462, 0.2855],
         [0.5920, 0.9858, 0.1338, 0.5780, 0.6108],
         [0.6089, 0.0334, 0.4411, 0.8925, 0.9013],
         [0.2234, 0.9520, 0.5424, 0.8083, 0.2212]]])

In [15]:
n = 5
for i in range(n):
  random_tensor = torch.rand(3,3)
  print(random_tensor)

tensor([[0.5383, 0.6847, 0.2005],
        [0.5304, 0.7643, 0.6682],
        [0.6234, 0.8895, 0.7920]])
tensor([[6.9730e-01, 6.6061e-01, 6.2792e-01],
        [1.7130e-01, 9.3455e-01, 5.8699e-04],
        [2.9534e-01, 3.3375e-01, 5.1968e-01]])
tensor([[0.5257, 0.2305, 0.7219],
        [0.3538, 0.3927, 0.2619],
        [0.7282, 0.0106, 0.7066]])
tensor([[0.5762, 0.5973, 0.2295],
        [0.4950, 0.3002, 0.2242],
        [0.1869, 0.4333, 0.3737]])
tensor([[0.5396, 0.7434, 0.3412],
        [0.9905, 0.6530, 0.6694],
        [0.8564, 0.8906, 0.9161]])


In [16]:
for i in range(n):
  random_tensor = torch.rand(5,4)
  print(random_tensor)

tensor([[0.5585, 0.5660, 0.8989, 0.6308],
        [0.0647, 0.2330, 0.1380, 0.5642],
        [0.6088, 0.7917, 0.1962, 0.2597],
        [0.8626, 0.5159, 0.9060, 0.1130],
        [0.9408, 0.4799, 0.5920, 0.3990]])
tensor([[0.2614, 0.1679, 0.6810, 0.6982],
        [0.7118, 0.7205, 0.4009, 0.5051],
        [0.5392, 0.1447, 0.8031, 0.9355],
        [0.3881, 0.7123, 0.1437, 0.3263],
        [0.2420, 0.6489, 0.1962, 0.3776]])
tensor([[0.5849, 0.4757, 0.6158, 0.3942],
        [0.3333, 0.6653, 0.3232, 0.1749],
        [0.5376, 0.6012, 0.4402, 0.2434],
        [0.3032, 0.5947, 0.1568, 0.7256],
        [0.2678, 0.8911, 0.7522, 0.7614]])
tensor([[0.3009, 0.1010, 0.8770, 0.1026],
        [0.4975, 0.2972, 0.1845, 0.8577],
        [0.1044, 0.5431, 0.7245, 0.9761],
        [0.1326, 0.2515, 0.0157, 0.2989],
        [0.2765, 0.4950, 0.2218, 0.2880]])
tensor([[0.4364, 0.1584, 0.4109, 0.4480],
        [0.3591, 0.6778, 0.2147, 0.0676],
        [0.8796, 0.7937, 0.3090, 0.5127],
        [0.6292, 0.3657, 0.407

In [17]:
random_tensor_size_tensor = torch.rand(size=(3,224,224)) # this is color channel , hieght , width
random_tensor_size_tensor.shape , random_tensor_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [18]:
print(random_tensor_size_tensor)

tensor([[[0.1387, 0.7657, 0.5164,  ..., 0.4409, 0.4194, 0.9338],
         [0.9200, 0.9982, 0.4254,  ..., 0.4917, 0.5270, 0.5354],
         [0.6525, 0.7106, 0.1012,  ..., 0.2171, 0.8628, 0.0250],
         ...,
         [0.1919, 0.5448, 0.3713,  ..., 0.9751, 0.9153, 0.6837],
         [0.5518, 0.6082, 0.7339,  ..., 0.1621, 0.0162, 0.1389],
         [0.5963, 0.7023, 0.6196,  ..., 0.2027, 0.4180, 0.1962]],

        [[0.6670, 0.9891, 0.5795,  ..., 0.0918, 0.4700, 0.6244],
         [0.3867, 0.6301, 0.1862,  ..., 0.6987, 0.9998, 0.0758],
         [0.3153, 0.6479, 0.1986,  ..., 0.8013, 0.3888, 0.8714],
         ...,
         [0.4721, 0.7227, 0.2307,  ..., 0.8648, 0.5582, 0.9748],
         [0.1975, 0.2047, 0.9869,  ..., 0.2026, 0.7087, 0.9226],
         [0.2065, 0.2185, 0.8976,  ..., 0.0553, 0.7200, 0.1953]],

        [[0.8620, 0.5017, 0.9874,  ..., 0.2056, 0.3581, 0.8784],
         [0.2317, 0.0020, 0.8098,  ..., 0.5914, 0.0849, 0.8340],
         [0.5367, 0.1175, 0.4882,  ..., 0.7018, 0.2467, 0.

In [19]:
zeros = torch.zeros(size=(3,6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,6))
ones


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [21]:
tensor_rand = torch.rand(size=(3,6))
tensor_rand , tensor_rand * zeros , tensor_rand * ones

(tensor([[0.6103, 0.6395, 0.7086, 0.9769, 0.0362, 0.4951],
         [0.5096, 0.8671, 0.5109, 0.2284, 0.5655, 0.2342],
         [0.1213, 0.7055, 0.5602, 0.8858, 0.3298, 0.9688]]),
 tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]),
 tensor([[0.6103, 0.6395, 0.7086, 0.9769, 0.0362, 0.4951],
         [0.5096, 0.8671, 0.5109, 0.2284, 0.5655, 0.2342],
         [0.1213, 0.7055, 0.5602, 0.8858, 0.3298, 0.9688]]))

In [22]:
tp_one = torch.arange(1,100)
tp_one

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
%%time
torch.matmul(float_16_tensor,float_16_tensor)

CPU times: user 1.09 ms, sys: 19 µs, total: 1.11 ms
Wall time: 7.52 ms


tensor(126., dtype=torch.float16)

In [28]:
torch.rand(3,4)

tensor([[0.4112, 0.4704, 0.3049, 0.8335],
        [0.9401, 0.2272, 0.3853, 0.7008],
        [0.4301, 0.1936, 0.4274, 0.0792]])

In [29]:
torch.rand(3,4)

tensor([[0.8888, 0.9466, 0.4348, 0.7750],
        [0.0497, 0.6831, 0.6919, 0.6141],
        [0.5106, 0.6539, 0.5550, 0.7674]])

In [30]:
torch.matmul(torch.rand(4,3),torch.rand(3,4))

tensor([[0.8758, 1.0149, 0.3270, 0.6499],
        [0.3904, 0.9262, 0.3887, 0.7973],
        [0.4579, 0.7704, 0.2613, 0.3858],
        [0.8933, 0.8630, 0.2764, 0.6803]])

In [31]:
torch_transpose = torch.rand(3,5)
torch_transpose

tensor([[0.6095, 0.2725, 0.3113, 0.0265, 0.2712],
        [0.5393, 0.5469, 0.0837, 0.6951, 0.3916],
        [0.5454, 0.6385, 0.7503, 0.9267, 0.0616]])

In [32]:
torch_transpose.T

tensor([[0.6095, 0.5393, 0.5454],
        [0.2725, 0.5469, 0.6385],
        [0.3113, 0.0837, 0.7503],
        [0.0265, 0.6951, 0.9267],
        [0.2712, 0.3916, 0.0616]])

In [41]:
torch_transpose.min()
torch.min(torch_transpose)
torch.argmin(torch_transpose)

tensor(0.0265)

In [42]:
torch_transpose[0][3]


tensor(0.0265)