In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


In [2]:
scalar = torch.tensor(5)
scalar

tensor(5)

**we get scalar number from tensor from dimension**

In [3]:
scalar.ndim
scalar.item()

5

In [4]:
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
matrix = torch.tensor([[3,5],
                       [4,2]])
matrix

tensor([[3, 5],
        [4, 2]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
print(matrix[1])
matrix[0]

tensor([4, 2])


tensor([3, 5])

In [11]:
TENSOR = torch.tensor([[[3,4,2],
                        [6,2,8],
                        [3,8,9]]])
TENSOR

tensor([[[3, 4, 2],
         [6, 2, 8],
         [3, 8, 9]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR.ndim

3

In [14]:
random_tensor = torch.rand(4,4,5)
random_tensor

tensor([[[0.9465, 0.1068, 0.5423, 0.4311, 0.8922],
         [0.8017, 0.6851, 0.0990, 0.4676, 0.8662],
         [0.9425, 0.2700, 0.2321, 0.0741, 0.2169],
         [0.2315, 0.3301, 0.9577, 0.4175, 0.7922]],

        [[0.5357, 0.1945, 0.4216, 0.7087, 0.1281],
         [0.6465, 0.9766, 0.5235, 0.3146, 0.0010],
         [0.5823, 0.9421, 0.3704, 0.1084, 0.1426],
         [0.1972, 0.8347, 0.8639, 0.1468, 0.1311]],

        [[0.0735, 0.0864, 0.5862, 0.7297, 0.4886],
         [0.1779, 0.7955, 0.0752, 0.1108, 0.8211],
         [0.4351, 0.0667, 0.1948, 0.7140, 0.3305],
         [0.7913, 0.4312, 0.5907, 0.9312, 0.8194]],

        [[0.5349, 0.2059, 0.5591, 0.2319, 0.9819],
         [0.1364, 0.4091, 0.9589, 0.4778, 0.3572],
         [0.8808, 0.9888, 0.6835, 0.8294, 0.1159],
         [0.5865, 0.5157, 0.1097, 0.1504, 0.4762]]])

In [15]:
n = 5
for i in range(n):
  random_tensor = torch.rand(3,3)
  print(random_tensor)

tensor([[0.4756, 0.4456, 0.0128],
        [0.6265, 0.2338, 0.9655],
        [0.7336, 0.4451, 0.3712]])
tensor([[0.7535, 0.2031, 0.2359],
        [0.3097, 0.3778, 0.1750],
        [0.3339, 0.5765, 0.5563]])
tensor([[0.6602, 0.0452, 0.4493],
        [0.9172, 0.9403, 0.5016],
        [0.7220, 0.9133, 0.5470]])
tensor([[0.3195, 0.7200, 0.1010],
        [0.8832, 0.0209, 0.1266],
        [0.9576, 0.2749, 0.7240]])
tensor([[0.6327, 0.0743, 0.1000],
        [0.7578, 0.5573, 0.9293],
        [0.5333, 0.2895, 0.2862]])


In [16]:
for i in range(n):
  random_tensor = torch.rand(5,4)
  print(random_tensor)

tensor([[0.0267, 0.4815, 0.3222, 0.0829],
        [0.2761, 0.4225, 0.8899, 0.5447],
        [0.8100, 0.2436, 0.6022, 0.3358],
        [0.0060, 0.7865, 0.8646, 0.6961],
        [0.3872, 0.2680, 0.7457, 0.9078]])
tensor([[0.7145, 0.2506, 0.3707, 0.4150],
        [0.2383, 0.8235, 0.1430, 0.6876],
        [0.6795, 0.6894, 0.4560, 0.1046],
        [0.3418, 0.8954, 0.8760, 0.0369],
        [0.9554, 0.4357, 0.3255, 0.6649]])
tensor([[0.7528, 0.9594, 0.2983, 0.6023],
        [0.4901, 0.2547, 0.0124, 0.4658],
        [0.2717, 0.9798, 0.1649, 0.1577],
        [0.6797, 0.0126, 0.3323, 0.8954],
        [0.3048, 0.1264, 0.2806, 0.4837]])
tensor([[0.9273, 0.5071, 0.4593, 0.5351],
        [0.7639, 0.3945, 0.5417, 0.2812],
        [0.2631, 0.7565, 0.4944, 0.6642],
        [0.9017, 0.7295, 0.7725, 0.4835],
        [0.4680, 0.6287, 0.1307, 0.4003]])
tensor([[0.6995, 0.1896, 0.5573, 0.1633],
        [0.2842, 0.4261, 0.3061, 0.7109],
        [0.1550, 0.9190, 0.4179, 0.3866],
        [0.2220, 0.9441, 0.487

In [17]:
random_tensor_size_tensor = torch.rand(size=(3,224,224)) # this is color channel , hieght , width
random_tensor_size_tensor.shape , random_tensor_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [18]:
print(random_tensor_size_tensor)

tensor([[[0.0289, 0.0371, 0.3701,  ..., 0.7301, 0.3399, 0.9715],
         [0.9126, 0.8378, 0.8045,  ..., 0.6105, 0.7546, 0.2890],
         [0.4509, 0.7019, 0.1275,  ..., 0.4977, 0.9727, 0.4044],
         ...,
         [0.9514, 0.7049, 0.0295,  ..., 0.7252, 0.6036, 0.8746],
         [0.4769, 0.6965, 0.6499,  ..., 0.6528, 0.5207, 0.7133],
         [0.8700, 0.0023, 0.2863,  ..., 0.7685, 0.9797, 0.6738]],

        [[0.8108, 0.4620, 0.0103,  ..., 0.5757, 0.8791, 0.2511],
         [0.3544, 0.4178, 0.5702,  ..., 0.7580, 0.1216, 0.0540],
         [0.3945, 0.8106, 0.1767,  ..., 0.9594, 0.8887, 0.8091],
         ...,
         [0.3226, 0.6473, 0.1559,  ..., 0.9606, 0.6667, 0.8446],
         [0.3041, 0.7804, 0.6135,  ..., 0.9938, 0.3686, 0.0102],
         [0.7354, 0.2151, 0.7942,  ..., 0.5980, 0.8436, 0.8372]],

        [[0.5761, 0.2809, 0.4564,  ..., 0.7126, 0.9445, 0.9035],
         [0.6229, 0.8376, 0.6721,  ..., 0.0681, 0.4278, 0.7953],
         [0.0707, 0.6942, 0.0146,  ..., 0.6787, 0.3966, 0.

In [19]:
zeros = torch.zeros(size=(3,6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,6))
ones


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [21]:
tensor_rand = torch.rand(size=(3,6))
tensor_rand , tensor_rand * zeros , tensor_rand * ones

(tensor([[0.0306, 0.0587, 0.9755, 0.4456, 0.2066, 0.7820],
         [0.4941, 0.1225, 0.5989, 0.2776, 0.8662, 0.7604],
         [0.0079, 0.9988, 0.9673, 0.0107, 0.5200, 0.5653]]),
 tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]),
 tensor([[0.0306, 0.0587, 0.9755, 0.4456, 0.2066, 0.7820],
         [0.4941, 0.1225, 0.5989, 0.2776, 0.8662, 0.7604],
         [0.0079, 0.9988, 0.9673, 0.0107, 0.5200, 0.5653]]))

In [22]:
tp_one = torch.arange(1,100)
tp_one

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
%%time
torch.matmul(float_16_tensor,float_16_tensor)

CPU times: user 0 ns, sys: 531 µs, total: 531 µs
Wall time: 6.73 ms


tensor(126., dtype=torch.float16)

In [28]:
torch.rand(3,4)

tensor([[0.6441, 0.9778, 0.5515, 0.0722],
        [0.8029, 0.2157, 0.8162, 0.0919],
        [0.4427, 0.4549, 0.7477, 0.4135]])

In [29]:
torch.rand(3,4)

tensor([[0.8669, 0.6413, 0.8283, 0.5759],
        [0.0403, 0.5663, 0.0398, 0.1714],
        [0.3632, 0.1301, 0.4578, 0.7553]])

In [30]:
torch.matmul(torch.rand(4,3),torch.rand(3,4))

tensor([[0.7717, 0.7260, 1.2659, 0.6281],
        [0.3002, 0.2532, 0.4606, 0.2516],
        [0.5824, 0.9346, 1.0384, 0.4841],
        [0.3086, 0.7201, 0.7357, 0.2196]])

In [31]:
torch_transpose = torch.rand(3,5)
torch_transpose

tensor([[0.8682, 0.1867, 0.1454, 0.1210, 0.3076],
        [0.2146, 0.5359, 0.5494, 0.2930, 0.3606],
        [0.0013, 0.4358, 0.9400, 0.0916, 0.7844]])

In [32]:
torch_transpose.T

tensor([[0.8682, 0.2146, 0.0013],
        [0.1867, 0.5359, 0.4358],
        [0.1454, 0.5494, 0.9400],
        [0.1210, 0.2930, 0.0916],
        [0.3076, 0.3606, 0.7844]])

In [33]:
torch_transpose.min()
torch.min(torch_transpose)
torch.argmin(torch_transpose)

tensor(10)

In [34]:
torch_transpose[0][3]


tensor(0.1210)

In [35]:
tensor_permute = torch.rand(size=(224,224,3))
tensor_permute

tensor([[[0.0918, 0.9540, 0.4863],
         [0.7520, 0.2981, 0.6500],
         [0.5324, 0.3724, 0.2437],
         ...,
         [0.6346, 0.5439, 0.4734],
         [0.0861, 0.1716, 0.9347],
         [0.0822, 0.7235, 0.6099]],

        [[0.5385, 0.4036, 0.3119],
         [0.6088, 0.1736, 0.1110],
         [0.8852, 0.8520, 0.8975],
         ...,
         [0.5751, 0.3225, 0.5793],
         [0.8877, 0.1857, 0.3481],
         [0.2380, 0.4832, 0.0167]],

        [[0.8697, 0.3441, 0.3999],
         [0.7610, 0.8335, 0.8771],
         [0.1260, 0.3815, 0.0882],
         ...,
         [0.2286, 0.2120, 0.4911],
         [0.8548, 0.3567, 0.3182],
         [0.6979, 0.6544, 0.1659]],

        ...,

        [[0.5411, 0.6308, 0.5135],
         [0.5295, 0.9639, 0.9134],
         [0.1039, 0.9551, 0.9074],
         ...,
         [0.6819, 0.2925, 0.8865],
         [0.2527, 0.6391, 0.9631],
         [0.2249, 0.5685, 0.5320]],

        [[0.4777, 0.3816, 0.9284],
         [0.3698, 0.8637, 0.6215],
         [0.

In [36]:
torch.permute(tensor_permute,(1,2,0)).shape

torch.Size([224, 3, 224])

In [37]:
# @title PyTorch Tensor and NumPy


In [38]:
array = np.arange(1.0,9.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

## Reproducbility (Trying to take random out of random)

To reduced the randomness in neural network and pytorch comes the concept of a
**Random seed**

In [39]:
import torch

random_torch_A = torch.rand(3,4)
random_torch_B = torch.rand(3,4)

print(random_torch_A)
print(random_torch_B)
print(random_torch_A == random_torch_B)


tensor([[0.6732, 0.8511, 0.7474, 0.5347],
        [0.0290, 0.9357, 0.1305, 0.0947],
        [0.3109, 0.6222, 0.1692, 0.0963]])
tensor([[0.7871, 0.9906, 0.1565, 0.6593],
        [0.8857, 0.0115, 0.3912, 0.0798],
        [0.5906, 0.9607, 0.2206, 0.5245]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [40]:
torch.rand(3,3)

tensor([[0.4843, 0.9358, 0.4848],
        [0.4766, 0.0138, 0.0926],
        [0.0188, 0.6391, 0.6502]])

In [41]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [42]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [43]:
torch.cuda.is_available()

False

In [44]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [45]:
torch.cuda.device_count()

0

In [46]:
tensor_device = torch.tensor([3,4,5])
print(tensor_device, tensor.device)

tensor([3, 4, 5]) cpu


In [47]:
tensor_on_gpu = tensor_device.to(device)
tensor_on_gpu

tensor([3, 4, 5])